### ISSUE TITLE
Stretched menu bar on Mavericks/Retina MBP

### ISSUE THREAD

**Issue by garymh** [CouleeApps/MenuBarFilter#2]
Love the work on the app! I seem to be having a problem getting it to work on my machine though. I'm using a 15" MBP retina with Mavericks and I get this on the menu bar:

![screen shot 2014-02-05 at 6 32 45p](https://f.cloud.github.com/assets/235202/2094180/5941f512-8ec6-11e3-910a-0e7af3615956.png)

I'd be happy to share any other info if you need it!

**Comment by CouleeApps** [comment]
Just tried it on my new rMBP and noticed this as well. Will investigate when I can.

**Comment by CouleeApps** [comment]
Seems to be fixed now.

**Comment by garymh** [comment]
Works great!! :thumbsup:
