### ISSUE TITLE
Full Screen Apps Issue

### ISSUE THREAD

**Issue by davidturner** [CouleeApps/MenuBarFilter#4]
Hi,

Firstly: It’s _amazing_ to see someone updating this app to work again. Thank you.

I’ve noticed an issue with full screen app menu bars. I’m not sure best to describe it… everything on the menubar seems to be slightly offset. I snapped a screenshot in case it helps:

![Full Screen Menu Bar Issue](http://dtrnr.in/h3d.png+/)

**Comment by CouleeApps** [comment]
That... is certainly something I've yet to see myself. Does this happen for you on every application? As well, are you using more than one monitor?

**Comment by CouleeApps** [comment]
Looks like it has to deal with Notification Center (the window I use for screen positioning) actually moving when in fullscreen mode.
![](http://cl.ly/image/271G0h2Z192U/Screen%20Shot%202014-02-25%20at%208.51.24%20PM.jpg)

**Comment by davidturner** [comment]
Interestingly the issue seems to have resolved itself for me, and everything is now lining up exactly how it should for me now. It was happening on every full-screen application, and I have only a single monitor. I am, however, using the Bartender App to remove/filter out certain menu bar apps, which could be a further complication of matters.

Whilst the previous issue seems to have worked itself out, I’ve encountered another full-screen apps issue. After showing the menu bar on a single full-screen app it seems that, when switching to another the app assumes that a menu bar will be there, even though it is hidden. I’ve uploaded a brief video of the issue. I apologise for the bizarre dimensions of it, and can upload a cropped version of the video if it would help. It can be found here: https://dl.dropboxusercontent.com/u/666229/full-screen-issue.mp4

**Comment by CouleeApps** [comment]
Oh I think I caused that when I "fixed" a different issue with menubar positioning. Let me just quickly iron that out.

**Comment by CouleeApps** [comment]
There, did something in c4ede19fd30fea0a840101e8589b1ae04d94773e that makes it at least check for full screen more often. Probably an easier way to do this.

**Comment by davidturner** [comment]
That’s sorted it. Thanks!
